name: Upload
slug: upload
version: dev
arch: [amd64, aarch64]
description: Test uploads
stage: experimental
init: false
ingress: true
ingress_stream: true
panel_icon: "mdi:test-tube"
panel_admin: false
